[tools]
# CLI tools
ghq = "latest"
jq = "latest"
fzf = "latest"
lazygit = "latest"
delta = "latest" # diff の表示を見やすくしてくれるツール
rg = "latest"
coreutils = "latest" # macOSは､BSD版なので､GNU版のほうが使い慣れているため｡
gh = "latest" # GitHub CLI
awscli = "latest"
gcloud = "latest"
act = "latest"
claude = "latest"
bun = "latest"
herdr = "latest" # AI エージェント用ターミナルマルチプレクサ

# For Go
go = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = { version = "latest" }
"github:k1LoW/roots" = "latest"
"github:d-kuro/gwq" = "latest"


# For Node.js
node = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@zed-industries/claude-code-acp" = "latest"
"npm:ccusage" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:@openai/codex" = "latest"
"npm:@ticktick/ticktick-cli" = "latest"

# For Rust
rust = "latest"
"github:rtk-ai/rtk" = "latest"

# For Lua
"cargo:selene" = "latest"
"cargo:tree-sitter-cli" = "latest"

# For Python
python = "latest"
"github:astral-sh/uv" = "latest"
poetry = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
