"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

palette = 'kanagawa_ink'

[directory]
style = "fg:crystal_blue"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:oni_violet"
format = 'on [$symbol $branch]($style) '

[git_status]
style = "fg:carp_yellow"
format = '([$all_status$ahead_behind]($style) )'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = "*"
untracked = "?"
staged = "+"
deleted = "✘"
conflicted = "!"
stashed = "\\$"

[cmd_duration]
show_milliseconds = true
format = " in [$duration]($style) "
style = "fg:fuji_gray"
disabled = false
show_notifications = false
min_time_to_notify = 45000

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:oni_violet)'
error_symbol = '[❯](bold fg:autumn_red)'
vimcmd_symbol = '[❮](bold fg:oni_violet)'
vimcmd_replace_one_symbol = '[❮](bold fg:sakura_pink)'
vimcmd_replace_symbol = '[❮](bold fg:sakura_pink)'
vimcmd_visual_symbol = '[❮](bold fg:carp_yellow)'

[palettes.kanagawa_ink]
oni_violet = "#957FB8"
crystal_blue = "#7E9CD8"
carp_yellow = "#E6C384"
sakura_pink = "#D27E99"
autumn_red = "#C34043"
fuji_gray = "#727169"
